# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ivocal-trainer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ivocal-trainer
  use_frameworks!
   pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  target 'Ivocal-trainerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ivocal-trainerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
